version: '3.8'

services:
  guest-management:
    build: .
    container_name: guest-management
    restart: unless-stopped
    volumes:
      - guest_data:/app/instance
      - guest_logs:/app/logs
    environment:
      - SECRET_KEY=${SECRET_KEY:-CHANGE-ME-IN-PORTAINER}
      - DATABASE_URL=${DATABASE_URL:-sqlite:////app/instance/guests.db}
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
      - MAIL_SERVER=${MAIL_SERVER:-}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USE_TLS=${MAIL_USE_TLS:-true}
      - MAIL_USERNAME=${MAIL_USERNAME:-}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN:-}
      - SLACK_CHANNEL_ID=${SLACK_CHANNEL_ID:-}
    networks:
      br0:
        ipv4_address: 192.168.1.150  # Your desired static IP
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    labels:
      - "app=guest-management"
      - "environment=production"
      - "maintainer=admin"

networks:
  br0:
    external: true  # Use existing network

volumes:
  guest_data:
    driver: local
  guest_logs:
    driver: local
