version: '3.8'

services:
  guest-management:
    build: .
    container_name: guest-management
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - guest_data:/app/instance
      - guest_logs:/app/logs
    environment:
      - SECRET_KEY=${SECRET_KEY:-your-random-secret-key-change-this}
      - DATABASE_URL=sqlite:///instance/guests.db
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    networks:
      - guest_network

networks:
  guest_network:
    driver: bridge

volumes:
  guest_data:
    driver: local
  guest_logs:
    driver: local
